version: "3"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: crawlerpass
      POSTGRES_DB: appcrawler
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: